version: '3.8'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "supersecret"
      REDASH_WEB_WORKERS: 4
    restart: unless-stopped
  worker:
    image: redash/redash:latest
    command: scheduler
    depends_on:
      - postgres
      - redis
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "supersecret"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: unless-stopped
  redis:
    image: redis:3.0-alpine
    volumes:
      - /data
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
  gw:
    build:
      dockerfile: Dockerfile.gw
      context: .
    command: ["gw", "--url", "http://server:5000", "--secrets", "/run/secrets/tunnel.json"]
    secrets:
      - tunnel.json
secrets:
  tunnel.json:
    file: secrets/tunnel.json